<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Xpf.Sdk/1.5.1">
    <PropertyGroup>
        <TargetFrameworks>net6.0-windows</TargetFrameworks>
        <OutputType>WinExe</OutputType>
        <UseWpf>true</UseWpf>
        <AssemblyName>LoadingIndicators.WPF.Demo</AssemblyName>
        <RootNamespace>LoadingIndicatorsDemo</RootNamespace>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>
    <PropertyGroup>
        <NoWarn>SA1652</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\LoadingIndicators.WPF\LoadingIndicators.WPF.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile DependentUpon="%(Filename)" SubType="Code" Update="**\obj\**\*.g$(DefaultLanguageSourceExtension)" />
        <Compile DependentUpon="%(Filename)" SubType="Designer" Update="**\*.xaml$(DefaultLanguageSourceExtension)" />
    </ItemGroup>
    <ItemGroup>
        <RuntimeHostConfigurationOption Include="AvaloniaUI.Xpf.LicenseKey" Value="$(XpfLicenseKey)"/>
    </ItemGroup>
</Project>