<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Xpf.Sdk/1.5.1">
  <PropertyGroup>
    <TargetFrameworks>net6.0-windows</TargetFrameworks>
    <AssemblyName>LoadingIndicators.WPF</AssemblyName>
    <Title>LoadingIndicators.WPF</Title>
    <RootNamespace>LoadingIndicators.WPF</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Compile DependentUpon="%(Filename)" SubType="Code" Update="**\obj\**\*.g$(DefaultLanguageSourceExtension)" />
    <Compile DependentUpon="%(Filename)" SubType="Designer" Update="**\*.xaml$(DefaultLanguageSourceExtension)" />
  </ItemGroup>

  <Target Name="_SdkDesignTimeBuildAndIntelliSenseWorkaround" AfterTargets="_CheckCompileDesignTimePrerequisite">
    <PropertyGroup>
      <BuildingProject>false</BuildingProject>
      <DesignTimeBuild>true</DesignTimeBuild>
    </PropertyGroup>
  </Target>
</Project>